# Информация о приложении
app:
  # Номер версии сборки МС
  version: "0.0.3"

  # Название приложения
  name: "ProxyCacheServer"

  # Отображаемое имя сервиса
  displayName: "Proxy Cache Server"

  # Описание сервиса
  description: "A proxy cache server written on the go-lang allows you to have hot cached data from external APIs"

# Данные для запуска http-сервера
server:
  host: "0.0.0.0"
  port: 8383

# Данные для запросов
request:
  # Интервал опроса по умолчанию
  interval: 3

  # Список прокси-серверов
  proxy:
    - http://185.82.218.47:1010
#    - http://163.172.215.220:80
#    - http://82.7.253.143:80
#    - https://89.236.17.108:3128
